name = "dermaclinicsnearme"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[build] # <--- Pages does NOT support this block
command = "npm run build"

[build.environment] # <--- Pages does NOT support this block
NODE_VERSION = "18"